name: Java Spring & MongoDB CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B clean install
        env:
          API_KEY: ${{ secrets.API_KEY }} 

      - name: Run tests with Maven
        run: mvn test
        env:
          spring_data_mongodb_host: localhost
          spring_data_mongodb_port: 27017
          spring_data_mongodb_database: events
          spring_redis_host: localhost
          spring_redis_port: 6379
          jwt_secret: ${{ secrets.API_KEY }} 
