name: Java Spring & MongoDB CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017


      mongo-express:
        image: mongo-express:latest
        ports:
          - 8081:8081
        env:
          ME_CONFIG_MONGODB_SERVER: mongodb
          ME_CONFIG_MONGODB_PORT: 27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'



      - name: Build with Maven
        run: mvn -B clean install
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Run tests with Maven
        run: mvn test
